name: python-app

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
            
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        # Commented out: Build steps
        
  test:
    runs-on: ubuntu-latest

    steps:    
      - name: Test with pytest
        run: |
          pytest
        
      - name: Archive test output 
        uses: actions/upload-artifact@v3
        with:
           name: test-output
           path: test-output/
         
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Deploy
        # Commented out: Deploy steps
