    - uses: ./.github/actions/run_tests

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test with pytest
        run: |
          if [ ! -f "/home/runner/work/xongptsh/main.py" ]; then
            echo "ERROR: File 'main.py' not found."
            exit 1
          fi

          cd /home/runner/work/xongptsh # Navigate to the directory
          python main.py > test-output.txt # Redirect output to a file
        with:
          name: test-output
          path: test-output.txt

      - name: Download artifacts
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          echo "Deploying application..."
          # Your deployment commands here
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/run_tests
