name: python-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          echo "Building application..."
          python setup.py build
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test with pytest
        run: |
          if [ ! -f "main.py" ]; then
            echo "ERROR: File 'main.py' not found."
            exit 1
          fi
      
          python main.py > test-output.txt  # Execute main.py using python notation

      - name: Archive test output
        if: success()
        run: |
          cp test-output.txt $GITHUB_WORKSPACE/test-output.txt

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          echo "Deploying application..."
          python deploy.py
