name: python-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Save main.py as artifact
        run: echo "::set-output name=filename::main.py"
        id: save-main-py

      - name: Upload main.py as artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-py
          path: ${{ steps.save-main-py.outputs.filename }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download main.py artifact
        uses: actions/download-artifact@v2
        with:
          name: main-py
          path: . # Save in the current directory

      - name: Build
        run: |
          echo "Building application..."
          python setup.py build
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download main.py artifact
        uses: actions/download-artifact@v2
        with:
          name: main-py
          path: . # Save in the current directory

      - name: Test with pytest
        run: |
          if [ ! -f "main.py" ]; then
            echo "ERROR: File 'main.py' not found."
            exit 1
          fi
      
          python main.py > test-output.txt  # Execute main.py using python notation

      - name: Archive test output
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: test-output.txt

      - name: Display downloaded artifact content
        run: cat test-output.txt # Display the content of the test output

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download main.py artifact
        uses: actions/download-artifact@v2
        with:
          name: main-py
          path: . # Save in the current directory

      - name: Deploy
        run: |
          echo "Deploying application..."
          python deploy.py
