name: python-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          echo "Building application..."
          python setup.py build
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test with pytest
        run: |
          python main.py > test-output.txt || true  # Continue even if the test fails

      - name: Archive test output
        if: always()  # Archive the output regardless of the test success or failure
        run: |
          cp test-output.txt $GITHUB_WORKSPACE/test-output.txt

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          echo "Deploying application..."
          python deploy.py
