name: python-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          echo "Building application..."
          # build commands here

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test with pytest
        run: |
          if [ ! -f "/home/runner/work/xongptsh/main.py" ]; then
            echo "ERROR: File 'main.py' not found."
            exit 1
          fi

          cd /home/runner/work/xongptsh # Navigate to the directory
          python main.py > test-output.txt # Redirect output to a file

      - name: Archive test output
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: test-output.txt

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-output
          path: downloaded-artifact # Path to download the artifact

      - name: Display downloaded artifact content
        run: cat downloaded-artifact/test-output.txt # Display the content of the downloaded artifact

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          echo "Deploying application..."
          # Your deployment commands here
